/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package e_wallet;



import java.security.*;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author Sam
 */
public class Controller extends javax.swing.JFrame {
    
    boolean loginStatus=false;
    String name;
    String bits_id;
    String password;
    int pin;
    String uname;
    String update;
    double amount=0;
    double rechargeAmount=0;

    /**
     *
     */
    public static int trycount=0;

    /**
     *
     */
    public static int warning = 0;

    /**
     *
     */
    public static int transactionID;

    /**
     *
     */
    public static int transactionIDStudent;
    boolean valid;
    JPasswordField pwd = new JPasswordField();
    
    /**
     *
     */
    public static ApplicationContext context = 
            new ClassPathXmlApplicationContext("Beans.xml");

    /**
     *
     */
    public static Database db = 
   	      (Database)context.getBean("db");
    /**
     * Creates new form Controller
     */
    public Controller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginVendorFrame = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        loginStudentFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bits_idField = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        login1 = new javax.swing.JButton();
        vendorFrame = new javax.swing.JFrame();
        receivePaymentButton = new javax.swing.JButton();
        checkBalanceButton0 = new javax.swing.JButton();
        logsButton0 = new javax.swing.JButton();
        last5trans = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        exitButton0 = new javax.swing.JButton();
        studentFrame = new javax.swing.JFrame();
        rechargeButton = new javax.swing.JButton();
        checkBalanceButton1 = new javax.swing.JButton();
        logsButton1 = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        loyaltyButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        last5trans1 = new javax.swing.JButton();
        adminFrame = new javax.swing.JFrame();
        createStudent = new javax.swing.JButton();
        createVendor = new javax.swing.JButton();
        deleteStudent = new javax.swing.JButton();
        deleteVendor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        exitButton2 = new javax.swing.JButton();
        createStudentFrame = new javax.swing.JFrame();
        nameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        pinField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        createStudentButton = new javax.swing.JButton();
        createVendorFrame = new javax.swing.JFrame();
        nameField1 = new javax.swing.JTextField();
        idField1 = new javax.swing.JTextField();
        passfield1 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        createVendorButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vendorButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        loginVendorFrame.setTitle("Login");
        loginVendorFrame.setBackground(new java.awt.Color(51, 123, 154));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setLabelFor(unameField);
        jLabel3.setText("Enter Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel4.setLabelFor(passwordField);
        jLabel4.setText("Enter Password");

        login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginVendorFrameLayout = new javax.swing.GroupLayout(loginVendorFrame.getContentPane());
        loginVendorFrame.getContentPane().setLayout(loginVendorFrameLayout);
        loginVendorFrameLayout.setHorizontalGroup(
            loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginVendorFrameLayout.createSequentialGroup()
                .addGroup(loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginVendorFrameLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unameField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginVendorFrameLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        loginVendorFrameLayout.setVerticalGroup(
            loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginVendorFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(loginVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        loginStudentFrame.setTitle("Login");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel5.setLabelFor(bits_idField);
        jLabel5.setText("Enter BITS ID No.");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel6.setLabelFor(passwordField1);
        jLabel6.setText("Enter Password");

        login1.setText("Login");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginStudentFrameLayout = new javax.swing.GroupLayout(loginStudentFrame.getContentPane());
        loginStudentFrame.getContentPane().setLayout(loginStudentFrameLayout);
        loginStudentFrameLayout.setHorizontalGroup(
            loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginStudentFrameLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bits_idField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(loginStudentFrameLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginStudentFrameLayout.setVerticalGroup(
            loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginStudentFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bits_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        vendorFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        receivePaymentButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        receivePaymentButton.setText("Receive Payment");
        receivePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivePaymentButtonActionPerformed(evt);
            }
        });

        checkBalanceButton0.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        checkBalanceButton0.setText("Check Balance");
        checkBalanceButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButton0ActionPerformed(evt);
            }
        });

        logsButton0.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logsButton0.setText("View Logs");
        logsButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsButton0ActionPerformed(evt);
            }
        });

        last5trans.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        last5trans.setText("Check Last 5 Transactions ");
        last5trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last5transActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("What would you like to do today?");

        exitButton0.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        exitButton0.setText("Logout");
        exitButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vendorFrameLayout = new javax.swing.GroupLayout(vendorFrame.getContentPane());
        vendorFrame.getContentPane().setLayout(vendorFrameLayout);
        vendorFrameLayout.setHorizontalGroup(
            vendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorFrameLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(vendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBalanceButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logsButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last5trans)
                    .addGroup(vendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(receivePaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        vendorFrameLayout.setVerticalGroup(
            vendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendorFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(receivePaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBalanceButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logsButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(last5trans, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        studentFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rechargeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rechargeButton.setText("Recharge");
        rechargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechargeButtonActionPerformed(evt);
            }
        });

        checkBalanceButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        checkBalanceButton1.setText("Check Balance");
        checkBalanceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButton1ActionPerformed(evt);
            }
        });

        logsButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logsButton1.setText("View Logs");
        logsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsButton1ActionPerformed(evt);
            }
        });

        exitButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        exitButton1.setText("Logout");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        loyaltyButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        loyaltyButton.setText("Redeem Loyalty Points");
        loyaltyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loyaltyButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("What would you like to do today?");

        last5trans1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        last5trans1.setText("Check Last 5 Transactions ");
        last5trans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last5trans1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentFrameLayout = new javax.swing.GroupLayout(studentFrame.getContentPane());
        studentFrame.getContentPane().setLayout(studentFrameLayout);
        studentFrameLayout.setHorizontalGroup(
            studentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentFrameLayout.createSequentialGroup()
                .addGroup(studentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentFrameLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel8))
                    .addGroup(studentFrameLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(studentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rechargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBalanceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loyaltyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(last5trans1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        studentFrameLayout.setVerticalGroup(
            studentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(rechargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBalanceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loyaltyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(last5trans1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        adminFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createStudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        createStudent.setText("Create Student");
        createStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentActionPerformed(evt);
            }
        });

        createVendor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        createVendor.setText("Create Vendor");
        createVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVendorActionPerformed(evt);
            }
        });

        deleteStudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteStudent.setText("Delete Student");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });

        deleteVendor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteVendor.setText("Delete Vendor");
        deleteVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVendorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("What would you like to do today?");

        exitButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        exitButton2.setText("Logout");
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminFrameLayout = new javax.swing.GroupLayout(adminFrame.getContentPane());
        adminFrame.getContentPane().setLayout(adminFrameLayout);
        adminFrameLayout.setHorizontalGroup(
            adminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminFrameLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(adminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(createVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(deleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(exitButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(deleteVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        adminFrameLayout.setVerticalGroup(
            adminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFrameLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(createStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jLabel11.setText("Name");

        jLabel12.setText("BITS ID");

        jLabel13.setText("Password");

        jLabel14.setText("PIN(4 digit Integral value)");

        createStudentButton.setBackground(new java.awt.Color(255, 255, 255));
        createStudentButton.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        createStudentButton.setText("Create");
        createStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createStudentFrameLayout = new javax.swing.GroupLayout(createStudentFrame.getContentPane());
        createStudentFrame.getContentPane().setLayout(createStudentFrameLayout);
        createStudentFrameLayout.setHorizontalGroup(
            createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createStudentFrameLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(passfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pinField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(createStudentFrameLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(createStudentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createStudentFrameLayout.setVerticalGroup(
            createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createStudentFrameLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(41, 41, 41)
                .addGroup(createStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(createStudentButton)
                .addGap(30, 30, 30))
        );

        jLabel15.setText("Name");

        jLabel16.setText("Username");

        jLabel17.setText("Password");

        createVendorButton.setBackground(new java.awt.Color(255, 255, 255));
        createVendorButton.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        createVendorButton.setText("Create");
        createVendorButton.setToolTipText("");
        createVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVendorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createVendorFrameLayout = new javax.swing.GroupLayout(createVendorFrame.getContentPane());
        createVendorFrame.getContentPane().setLayout(createVendorFrameLayout);
        createVendorFrameLayout.setHorizontalGroup(
            createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createVendorFrameLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(99, 99, 99)
                .addGroup(createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passfield1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(createVendorFrameLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(createVendorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createVendorFrameLayout.setVerticalGroup(
            createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createVendorFrameLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(35, 35, 35)
                .addGroup(createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(41, 41, 41)
                .addGroup(createVendorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(createVendorButton)
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Wallet BITS Goa");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Welcome User!");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setLabelFor(this);
        jLabel2.setText("Who Are You?");

        vendorButton.setBackground(new java.awt.Color(255, 255, 255));
        vendorButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vendorButton.setText("Vendor");
        vendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorButtonActionPerformed(evt);
            }
        });

        studentButton.setBackground(new java.awt.Color(255, 255, 255));
        studentButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        studentButton.setText("Student");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(vendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorButtonActionPerformed
        loginVendorFrame.pack();
        //this.setVisible(false);
        loginVendorFrame.setVisible(true);
        loginVendorFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_vendorButtonActionPerformed
    //for vendor
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        uname = unameField.getText();
        uname = uname.toLowerCase();
        password = toHash(passwordField.getText());
        loginVendor();
        if(loginStatus){
            vendorFrame.pack();
            vendorFrame.setTitle("Welcome "+name+"!");
            loginVendorFrame.setVisible(false);
            this.setVisible(false);
            vendorFrame.setVisible(true);
            vendorFrame.setLocationRelativeTo(null);
        }
        else
            JOptionPane.showMessageDialog(loginVendorFrame,"No Such Vendor Exists");
            
    }//GEN-LAST:event_loginActionPerformed
    //for student
    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        bits_id = bits_idField.getText();
        bits_id = bits_id.toLowerCase();
        password = toHash(passwordField1.getText());
        loginStudent();
        if(loginStatus){
            studentFrame.pack();
            studentFrame.setTitle("Welcome "+name+"!");
            loginStudentFrame.setVisible(false);
            this.setVisible(false);
            studentFrame.setVisible(true);
            studentFrame.setLocationRelativeTo(null);
        }
        else
            JOptionPane.showMessageDialog(loginStudentFrame,"No Such Student Exists");
    }//GEN-LAST:event_login1ActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        loginStudentFrame.pack();
        loginStudentFrame.setVisible(true);
        loginStudentFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_studentButtonActionPerformed

    private void checkBalanceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButton1ActionPerformed
        JOptionPane.showMessageDialog(studentFrame,
        "Your current E-Wallet Balance is Rs."+db.checkBalance(bits_id),
        "Update",
        JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_checkBalanceButton1ActionPerformed

    private void receivePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivePaymentButtonActionPerformed
        PaymentTracker ptracker  = new PaymentTracker(uname);
        Vendor vendor = db.getVendor(uname);
        boolean valid = true;
        Student student;
        
            try {
                amount = Double.parseDouble(JOptionPane.showInputDialog(vendorFrame,"Enter amount", "Input Amount",JOptionPane.PLAIN_MESSAGE));
                
            } catch (NumberFormatException e) {
            //error
                valid=false;
                JOptionPane.showMessageDialog(vendorFrame,"Error, not a valid input. Please try again.","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(valid){
                int i = JOptionPane.showConfirmDialog(vendorFrame,
                "You have requested Rs."+amount+" Is that correct?", "Confirm Amount", JOptionPane.YES_NO_OPTION);
                valid = i==0;
            }
            if(valid){
                ReceivePayment r2 = ptracker.initiateTransaction(amount);
                
                while(trycount<3){
                        bits_id = JOptionPane.showInputDialog(null,"Enter Student ID", "Input",JOptionPane.PLAIN_MESSAGE);
                        bits_id = bits_id.toLowerCase();
                        if(Controller.db.verifyIDExists(1,bits_id)){
                                student = Controller.db.getStudent(bits_id);
                                
                                if(r2.checkAmount(amount,student)){
                                        if(getPIN()){
                                            update = r2.transferAmount(student,amount,pin);
                                            if(warning==0)
                                                JOptionPane.showMessageDialog(null,
                                                update,"Update",
                                                JOptionPane.PLAIN_MESSAGE);
                                            else
                                                JOptionPane.showMessageDialog(null,
                                                update,"Incorrect PIN",
                                                JOptionPane.WARNING_MESSAGE);
                                        }
                                }
                                else{
                                        int i = JOptionPane.showConfirmDialog(null,
                                        "The amount entered exceeds your E-Wallet Balance. Would you like to Recharge?", "Insufficient Balance", JOptionPane.YES_NO_OPTION);
			
                                        switch(i){//resume editing from here
                                            case 0:pwd.setText("");
                                                int action = JOptionPane.showConfirmDialog(null, pwd,"Enter Password",JOptionPane.OK_CANCEL_OPTION);
                                                if (action == JOptionPane.OK_OPTION) {
                                                password = toHash(new String(pwd.getPassword()));
                                                }
                                                if(Controller.db.verifyPassword(student, password)){
                                                    PaymentTracker pt2=new PaymentTracker(bits_id);
                                                    Recharge r1 = pt2.initiateRecharge(amount);
                                                    db.deleteLog(transactionIDStudent);
                                                    recharge();
                                                    trycount=0;
                                                }
                                                else{
                                                    JOptionPane.showMessageDialog(null,"Entered password is incorrect","Incorrect Password",JOptionPane.WARNING_MESSAGE);
                                                    break;
                                                }break;
					
                                            case 1:break;
                                        }
                                }
                        }
                        else
                            JOptionPane.showMessageDialog(null,"No such student exists","Invalid ID",JOptionPane.ERROR_MESSAGE);
                            
                }
            } 
    }//GEN-LAST:event_receivePaymentButtonActionPerformed

    private void checkBalanceButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButton0ActionPerformed
            JOptionPane.showMessageDialog(vendorFrame,
            "Your current E-Wallet Balance is Rs."+db.checkBalanceVendor(uname),
            "Update",
            JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_checkBalanceButton0ActionPerformed

    private void last5transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last5transActionPerformed
        lastTransactions(uname);    
    }//GEN-LAST:event_last5transActionPerformed

    private void rechargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechargeButtonActionPerformed
        recharge();
    }//GEN-LAST:event_rechargeButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void logsButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButton0ActionPerformed
        viewLogs(uname);
    }//GEN-LAST:event_logsButton0ActionPerformed

    private void logsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButton1ActionPerformed
        viewLogs(bits_id);
    }//GEN-LAST:event_logsButton1ActionPerformed

    private void exitButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton0ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton0ActionPerformed

    private void last5trans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last5trans1ActionPerformed
        lastTransactions(bits_id);
    }//GEN-LAST:event_last5trans1ActionPerformed

    private void loyaltyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loyaltyButtonActionPerformed
        Student student = Controller.db.getStudent(bits_id);
        student.ewbalance+=student.loyaltyBonus;
        
        Controller.db.updateBalance(bits_id, student.ewbalance, student.swdbalance);
        transactionIDStudent = Controller.db.createLog(bits_id, student.loyaltyBonus, new Date(),0);
        Controller.db.updateLog(transactionIDStudent,null,new Date(),1);
        Controller.db.updateLog(transactionIDStudent,"Loyalty Benefits Redeemed", new Date(), student.ewbalance);
        student.loyaltyBonus = 0;
        JOptionPane.showMessageDialog(null,Controller.db.updatelb(bits_id, pin));
    }//GEN-LAST:event_loyaltyButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int action = JOptionPane.showConfirmDialog(null, pwd,"Enter Password",JOptionPane.OK_CANCEL_OPTION);
            if (action == JOptionPane.OK_OPTION) {
            password = new String(pwd.getPassword());
            valid = true;
            }
        }
        catch(NullPointerException e){
                                                   
        }
        if(valid){
            if(password.equals("group6")){
            adminFrame.pack();
            adminFrame.setVisible(true);
            adminFrame.setLocationRelativeTo(null);
            }
            else
                JOptionPane.showMessageDialog(null, "Wrong Password","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentActionPerformed
        createStudentFrame.pack();
        this.setVisible(false);
        createStudentFrame.setVisible(true);
        createStudentFrame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_createStudentActionPerformed

    private void createVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVendorActionPerformed
        createVendorFrame.pack();
        this.setVisible(false);
        createVendorFrame.setVisible(true);
        createVendorFrame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_createVendorActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        bits_id = JOptionPane.showInputDialog(null,"Enter Student ID", "Delete Student",JOptionPane.PLAIN_MESSAGE);
                        bits_id = bits_id.toLowerCase();
                        JOptionPane.showMessageDialog(null,Controller.db.delete(1, bits_id));
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void deleteVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVendorActionPerformed
        uname = JOptionPane.showInputDialog(null,"Enter Username", "Delete Vendor",JOptionPane.PLAIN_MESSAGE);
                        uname = uname.toLowerCase();
                        JOptionPane.showMessageDialog(null,Controller.db.delete(2, uname));
    }//GEN-LAST:event_deleteVendorActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void createVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVendorButtonActionPerformed
        nameField1.setText("");
        idField1.setText("");
        passfield1.setText("");
        name = nameField1.getText();
        uname = idField1.getText();
        uname = uname.toLowerCase();
        password = toHash(passfield1.getText());
        JOptionPane.showMessageDialog(null,Controller.db.create(name, uname, password));
        createVendorFrame.setVisible(false);
    }//GEN-LAST:event_createVendorButtonActionPerformed

    private void createStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentButtonActionPerformed
        nameField.setText("");
        idField.setText("");
        passfield.setText("");
        pinField.setText("");
        name = nameField.getText();
        bits_id = idField.getText();
        bits_id = bits_id.toLowerCase();
        password = toHash(passfield.getText());
        try {
                pin = Integer.parseInt(pinField.getText());
                valid = true;
                
        }catch (NumberFormatException e) {
                //error
                valid=false;
        }
        if(valid)
            JOptionPane.showMessageDialog(null,Controller.db.create(name, bits_id, password, pin));
        else
            JOptionPane.showMessageDialog(null,"Incorrect PIN format", "Try Again",JOptionPane.WARNING_MESSAGE);
        
        createStudentFrame.setVisible(false);
    }//GEN-LAST:event_createStudentButtonActionPerformed

    /**
     *
     */
    public void recharge(){
        PaymentTracker ptracker  = new PaymentTracker(bits_id);
        Student student = db.getStudent(bits_id);
        try {
                rechargeAmount = Double.parseDouble(JOptionPane.showInputDialog(null,"Your Current E-Wallet Balance is Rs."+student.ewbalance+"\n"+ "Your Current SWD Balance is Rs."+student.swdbalance,"Enter Recharge Amount",JOptionPane.PLAIN_MESSAGE));
                valid = true;
                
        }catch (NumberFormatException e) {
                //error
                valid=false;
                JOptionPane.showMessageDialog(null,"Error, not a valid input. Please try again.","Error",JOptionPane.ERROR_MESSAGE);
                
        }
        if(valid){
            Recharge r1 = ptracker.initiateRecharge(rechargeAmount);
        
            while(trycount<=2){
                if(r1.checkAmount(rechargeAmount)){
                    if(getPIN()){
                        update = r1.rechargeAccount(rechargeAmount,pin);
                        if(warning==0)
                            JOptionPane.showMessageDialog(null,
                                update,"Update",
                                JOptionPane.PLAIN_MESSAGE);
                        else
                            JOptionPane.showMessageDialog(null,
                                update,"Incorrect PIN",
                                JOptionPane.WARNING_MESSAGE);
                    }
                }
                else{
                        int i = JOptionPane.showConfirmDialog(null,
                        "The amount entered exceeds your SWD Balance. would you like to avail credit?", "Confirm Amount", JOptionPane.YES_NO_OPTION);
                        switch(i){
                            case 0:JOptionPane.showMessageDialog(null,"According to your requested amount you would like to take Credit for Rs."+(rechargeAmount-student.swdbalance)+"\n"+ "Available Credits Rs."+student.credit_avail,"Update",JOptionPane.PLAIN_MESSAGE);
                                if(r1.checkCreditAmount(rechargeAmount)){
                                    if(getPIN()){
                                        update = r1.takeCredit(rechargeAmount,pin);
                                        if(warning==0)
                                                JOptionPane.showMessageDialog(null,
                                                update,"Update",
                                                JOptionPane.PLAIN_MESSAGE);
                                        else
                                                JOptionPane.showMessageDialog(null,
                                                update,"Incorrect PIN",
                                                JOptionPane.WARNING_MESSAGE);
                                    }
                                }
                                else{
                
                                    i = JOptionPane.showConfirmDialog(null,
                                    "You don't have enough credits available\nWould you like to try again.?", "Try Again?",
                                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                                    if(i!=0){
                                    update = "Recharge Cancelled";
                                    Controller.db.updateLog(Controller.transactionIDStudent,update, new Date(), student.ewbalance);
                                    trycount=10;
                                    }
                                    else
                                        recharge();
                                }
                                break;
				
                            case 1:
                                JOptionPane.showMessageDialog(null,
                                "Okay. Exiting to main menu...");	
				update = "Recharge Cancelled";
				Controller.db.updateLog(Controller.transactionIDStudent,update, new Date(), student.ewbalance);
				trycount=10;
                                
                        }
                    
                    }
            }
        }
            
    }
    private boolean getPIN(){
        pwd.setText("");
                try {
                    int action = JOptionPane.showConfirmDialog(null, pwd,"Enter PIN",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
                    if (action == JOptionPane.OK_OPTION) {
                    pin = Integer.parseInt(new String(pwd.getPassword()));
                    valid=true;
                    }
                    else if(action == 2){
                        valid = false;
                        trycount=10;
                    }
                        
                } catch (NumberFormatException e) {
                    //error
                    valid=false;
                    JOptionPane.showMessageDialog(null,"The Entered PIN is incorrect.You have "+(2-trycount)+" tries left","Incorrect PIN",JOptionPane.WARNING_MESSAGE);
                    trycount++;
                    
                }
                return valid;
    }
    
    private void lastTransactions(String lcred){
        final JTextArea textArea = new JTextArea(20, 40);
        String title = "Log for "+lcred;
        List<Transactions> list  = Controller.db.last5Transactions(lcred);
        for(Transactions t : list){
            if(t.type == 0){
                if(t.completion == -1)
                    textArea.append("\nUnsuccessful Recharge: \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
                else
                    textArea.append("\nSuccessful Recharge: \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
            }
            else
                if(t.completion == -1)
                    textArea.append("\nUnsuccessful Transaction to "+t.to+": \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
                else
                    textArea.append("\nSuccessful Transaction to "+t.to+": \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
            textArea.append("\n");      
        }
        JOptionPane.showMessageDialog(null, new JScrollPane(textArea),title,JOptionPane.PLAIN_MESSAGE);
    }
    
    private void viewLogs(String lcred){
        final JTextArea textArea = new JTextArea(20, 40);
        String title = "Log for "+lcred;
        List<Transactions> list  = Controller.db.findAllEntries(lcred);
        for(Transactions t : list){
            if(t.type == 0){
                if(t.completion == -1)
                    textArea.append("\nUnsuccessful Recharge: \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
                else
                    textArea.append("\nSuccessful Recharge: \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
            }
            else
                if(t.completion == -1)
                    textArea.append("\nUnsuccessful Transaction to "+t.to+": \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
                else
                    textArea.append("\nSuccessful Transaction to "+t.to+": \nStart time "+t.start+" End time "+t.end+" Amount:"+t.amount+"\nComments "+t.comments+"\nE-Wallet Balance: Rs."+t.balance);
            textArea.append("\n");      
        }
        JOptionPane.showMessageDialog(null, new JScrollPane(textArea),title,JOptionPane.PLAIN_MESSAGE);
        
    }
    private void loginStudent(){
		Login l = new Login(bits_id,password);
		if(l.resultStudent()){
			name=l.getStudentName();
			loginStatus=true;
		}else
			loginStatus=false;
	}
    
    private void loginVendor(){
		Login l = new Login(uname,password);
		if(l.resultVendor()){
			name=l.getVendorName();
			loginStatus=true;
		}else
			loginStatus=false;
	}
    
    static String toHash(String pass){
    	StringBuffer sb = new StringBuffer();
    	MessageDigest md; 
    	try{
    		md = MessageDigest.getInstance("MD5");
    		md.update(pass.getBytes());
    		byte byteData[] = md.digest();
 
    		//convert the byte to hex format method 1
    		sb = new StringBuffer();
    		for (int i = 0; i < byteData.length; i++) {
    			sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
    		}
    		
    	}catch(NoSuchAlgorithmException e){
    		
    	}
    	return sb.toString();
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame adminFrame;
    private javax.swing.JTextField bits_idField;
    private javax.swing.JButton checkBalanceButton0;
    private javax.swing.JButton checkBalanceButton1;
    private javax.swing.JButton createStudent;
    private javax.swing.JButton createStudentButton;
    private javax.swing.JFrame createStudentFrame;
    private javax.swing.JButton createVendor;
    private javax.swing.JButton createVendorButton;
    private javax.swing.JFrame createVendorFrame;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JButton deleteVendor;
    private javax.swing.JButton exitButton0;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton last5trans;
    private javax.swing.JButton last5trans1;
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JFrame loginStudentFrame;
    private javax.swing.JFrame loginVendorFrame;
    private javax.swing.JButton logsButton0;
    private javax.swing.JButton logsButton1;
    private javax.swing.JButton loyaltyButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JPasswordField passfield1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton receivePaymentButton;
    private javax.swing.JButton rechargeButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JFrame studentFrame;
    private javax.swing.JTextField unameField;
    private javax.swing.JButton vendorButton;
    private javax.swing.JFrame vendorFrame;
    // End of variables declaration//GEN-END:variables
}
